### ISSUE TITLE
can you change pastebin links to another service. 

### ISSUE THREAD

**Issue by frosten** [AveYo/D-OPTIMIZER#1]
pastebin has been banned by turkish goverment. please add to all releated file in this repository.

**Comment by AveYo** [comment]
I can add them here and to onedrive _(that should work since it's Microsoft)_. 
Will take some time since I'm busy making the new Arcana Hotkeys release

**Comment by borbaszorbas** [comment]
Off topic but may I ask when we can expect the arcana hotkeys to be released because the steam guide was removed

**Comment by AveYo** [comment]
[pastebin_backup_20170502.zip](https://github.com/AveYo/D-OPTIMIZER/blob/c66bc927fe04f0c384315fefb64524905eae08ea/pastebin_backup_20170502.zip)
