### ISSUE TITLE
I think valve made some changed to Languages and the language mod doesnt work!

### ISSUE THREAD

**Issue by Dsr00715** [AveYo/D-OPTIMIZER#6]
This is regarding the Quickcast tp for advanced quickcast option. 
Would love it if u fix it again ty!!
My email is dsr07715@gmail.com ping me if u fix it !

**Comment by AveYo** [comment]
https://github.com/AveYo/D-OPTIMIZER/releases/tag/4.0.23

**Comment by Dsr00715** [comment]
Thanks!
